# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from click_and_drop_api.api.returns_api import ReturnsApi


class TestReturnsApi(unittest.TestCase):
    """ReturnsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReturnsApi()

    def tearDown(self) -> None:
        pass

    def test_returns_post(self) -> None:
        """Test case for returns_post

        Create a return shipment
        """
        pass

    def test_returns_services_get(self) -> None:
        """Test case for returns_services_get

        List available return services
        """
        pass


if __name__ == '__main__':
    unittest.main()
