# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from click_and_drop_api.api.carriers_api import CarriersApi


class TestCarriersApi(unittest.TestCase):
    """CarriersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CarriersApi()

    def tearDown(self) -> None:
        pass

    def test_get_carriers_async(self) -> None:
        """Test case for get_carriers_async

        Retrieve list of carriers for the account
        """
        pass


if __name__ == '__main__':
    unittest.main()
