# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from click_and_drop_api.models.create_return_request import CreateReturnRequest

class TestCreateReturnRequest(unittest.TestCase):
    """CreateReturnRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateReturnRequest:
        """Test CreateReturnRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateReturnRequest`
        """
        model = CreateReturnRequest()
        if include_optional:
            return CreateReturnRequest(
                service = click_and_drop_api.models.service_code.ServiceCode(
                    service_code = '', 
                    service_register_code = '', ),
                shipment = click_and_drop_api.models.shipment.Shipment(
                    shipping_address = click_and_drop_api.models.address.Address(
                        title = '', 
                        first_name = '', 
                        last_name = '', 
                        company_name = '', 
                        address_line1 = '', 
                        address_line2 = '', 
                        address_line3 = '', 
                        city = '', 
                        county = '', 
                        postcode = '', 
                        country = '', 
                        country_iso_code = '', ), 
                    return_address = click_and_drop_api.models.address.Address(
                        title = '', 
                        first_name = '', 
                        last_name = '', 
                        company_name = '', 
                        address_line1 = '', 
                        address_line2 = '', 
                        address_line3 = '', 
                        city = '', 
                        county = '', 
                        postcode = '', 
                        country = '', 
                        country_iso_code = '', ), 
                    customer_reference = click_and_drop_api.models.customer_reference.CustomerReference(
                        reference = '', ), )
            )
        else:
            return CreateReturnRequest(
                service = click_and_drop_api.models.service_code.ServiceCode(
                    service_code = '', 
                    service_register_code = '', ),
                shipment = click_and_drop_api.models.shipment.Shipment(
                    shipping_address = click_and_drop_api.models.address.Address(
                        title = '', 
                        first_name = '', 
                        last_name = '', 
                        company_name = '', 
                        address_line1 = '', 
                        address_line2 = '', 
                        address_line3 = '', 
                        city = '', 
                        county = '', 
                        postcode = '', 
                        country = '', 
                        country_iso_code = '', ), 
                    return_address = click_and_drop_api.models.address.Address(
                        title = '', 
                        first_name = '', 
                        last_name = '', 
                        company_name = '', 
                        address_line1 = '', 
                        address_line2 = '', 
                        address_line3 = '', 
                        city = '', 
                        county = '', 
                        postcode = '', 
                        country = '', 
                        country_iso_code = '', ), 
                    customer_reference = click_and_drop_api.models.customer_reference.CustomerReference(
                        reference = '', ), ),
        )
        """

    def testCreateReturnRequest(self):
        """Test CreateReturnRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
