# coding: utf-8

"""
ChannelShipper & Royal Mail Public API

Import your orders, retrieve your orders and generate labels.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from click_and_drop_api.models.create_packages_response import CreatePackagesResponse


class TestCreatePackagesResponse(unittest.TestCase):
    """CreatePackagesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePackagesResponse:
        """Test CreatePackagesResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreatePackagesResponse`
        """
        model = CreatePackagesResponse()
        if include_optional:
            return CreatePackagesResponse(
                package_number = 56,
                tracking_number = ''
            )
        else:
            return CreatePackagesResponse(
        )
        """

    def testCreatePackagesResponse(self):
        """Test CreatePackagesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
