# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from click_and_drop_api.models.get_services_response import GetServicesResponse

class TestGetServicesResponse(unittest.TestCase):
    """GetServicesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetServicesResponse:
        """Test GetServicesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetServicesResponse`
        """
        model = GetServicesResponse()
        if include_optional:
            return GetServicesResponse(
                services = [
                    click_and_drop_api.models.service_item.ServiceItem(
                        carrier_guid = 'e90e87c8-4ea6-49ec-a387-64ba37f66d84', 
                        carrier_service_guid = '3824a10c-1a2b-4e66-b82f-efa236a86cd9', 
                        service_name = 'Tracked Returns 24', 
                        service_code = 'TSN', )
                    ]
            )
        else:
            return GetServicesResponse(
        )
        """

    def testGetServicesResponse(self):
        """Test GetServicesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
