[tox]
envlist = py3

[testenv]
deps=
     -e .

commands=
     pip install "pip>=25.1"
     pip install --group test
     pytest

[testenv:release]
changedir=test
allowlist_externals=
     ls
     rm
deps=
     build
     pytest
commands=
     rm -rf dist
     python -m build --wheel --outdir dist .. 
     python -c "import os, glob; os.rename(glob.glob('dist/*.whl')[0], 'dist/click_and_drop_api-1.0.0-py3-none-any.whl')"
     pip install "pip>=25.1"
     pip install --force-reinstall dist/click_and_drop_api-1.0.0-py3-none-any.whl
     python -c "import click_and_drop_api; assert 'site-packages' in click_and_drop_api.__file__, click_and_drop_api.__file__"
     pytest .

