"""Sample valid addresses for every ISO 3166-1 alpha-2 country.

Each entry is an Address suitable for test orders.
Countries that do not use postal codes omit the postcode field.

Usage::

    from click_and_drop_api.simple.addresses import ADDRESSES, get_address

    addr = get_address("DE")          # by code
    addr = ADDRESSES["FR"]            # direct dict access
"""

from .types import Address


def get_address(country_code: str) -> Address:
    """Return the sample address for *country_code* (ISO 3166-1 alpha-2).

    Raises:
        KeyError: if the country code is unknown.
    """
    return ADDRESSES[country_code.upper()]


def get_all_country_codes() -> list[str]:
    """Return all known country codes (ISO 3166-1 alpha-2)."""
    return list(sorted(ADDRESSES.keys()))


ADDRESSES: dict[str, Address] = {
    "AD": Address(
        full_name="Test Recipient",
        address_line1="Carrer Major 1",
        city="Andorra la Vella",
        postcode="AD500",
        country_code="AD",
    ),
    "AE": Address(
        full_name="Test Recipient",
        address_line1="Sheikh Zayed Road 1",
        city="Dubai",
        country_code="AE",
    ),
    "AF": Address(
        full_name="Test Recipient",
        address_line1="Wazir Akbar Khan 1",
        city="Kabul",
        country_code="AF",
    ),
    "AG": Address(
        full_name="Test Recipient",
        address_line1="Thames Street 1",
        city="St. John's",
        country_code="AG",
    ),
    "AI": Address(
        full_name="Test Recipient",
        address_line1="The Valley Road 1",
        city="The Valley",
        country_code="AI",
    ),
    "AL": Address(
        full_name="Test Recipient",
        address_line1="Rruga e Dibres 1",
        city="Tirana",
        postcode="1001",
        country_code="AL",
    ),
    "AM": Address(
        full_name="Test Recipient",
        address_line1="Baghramyan Avenue 1",
        city="Yerevan",
        postcode="0019",
        country_code="AM",
    ),
    "AO": Address(
        full_name="Test Recipient",
        address_line1="Rua do 1° Congresso 1",
        city="Luanda",
        country_code="AO",
    ),
    "AQ": Address(
        full_name="Test Recipient",
        address_line1="McMurdo Station",
        city="Ross Island",
        country_code="AQ",
    ),
    "AR": Address(
        full_name="Test Recipient",
        address_line1="Avenida de Mayo 1",
        city="Buenos Aires",
        postcode="C1002",
        country_code="AR",
    ),
    "AS": Address(
        full_name="Test Recipient",
        address_line1="Fagatogo Square 1",
        city="Pago Pago",
        postcode="96799",
        country_code="AS",
    ),
    "AT": Address(
        full_name="Test Recipient",
        address_line1="Stephansplatz 1",
        city="Vienna",
        postcode="1010",
        country_code="AT",
    ),
    "AU": Address(
        full_name="Test Recipient",
        address_line1="1 Martin Place",
        city="Sydney",
        postcode="2000",
        country_code="AU",
    ),
    "AW": Address(
        full_name="Test Recipient",
        address_line1="L.G. Smith Boulevard 1",
        city="Oranjestad",
        country_code="AW",
    ),
    "AX": Address(
        full_name="Test Recipient",
        address_line1="Torggatan 1",
        city="Mariehamn",
        postcode="22100",
        country_code="AX",
    ),
    "AZ": Address(
        full_name="Test Recipient",
        address_line1="Istiqlaliyyat Street 1",
        city="Baku",
        postcode="AZ1001",
        country_code="AZ",
    ),
    "BA": Address(
        full_name="Test Recipient",
        address_line1="Marsala Tita 1",
        city="Sarajevo",
        postcode="71000",
        country_code="BA",
    ),
    "BB": Address(
        full_name="Test Recipient",
        address_line1="Broad Street 1",
        city="Bridgetown",
        country_code="BB",
    ),
    "BD": Address(
        full_name="Test Recipient",
        address_line1="Motijheel C/A 1",
        city="Dhaka",
        postcode="1000",
        country_code="BD",
    ),
    "BE": Address(
        full_name="Test Recipient",
        address_line1="Rue de la Loi 1",
        city="Brussels",
        postcode="1000",
        country_code="BE",
    ),
    "BF": Address(
        full_name="Test Recipient",
        address_line1="Avenue de la Nation 1",
        city="Ouagadougou",
        country_code="BF",
    ),
    "BG": Address(
        full_name="Test Recipient",
        address_line1="Vitosha Boulevard 1",
        city="Sofia",
        postcode="1000",
        country_code="BG",
    ),
    "BH": Address(
        full_name="Test Recipient",
        address_line1="Government Avenue 1",
        city="Manama",
        postcode="317",
        country_code="BH",
    ),
    "BI": Address(
        full_name="Test Recipient",
        address_line1="Boulevard du 28 Novembre 1",
        city="Bujumbura",
        country_code="BI",
    ),
    "BJ": Address(
        full_name="Test Recipient",
        address_line1="Avenue Jean-Paul II 1",
        city="Cotonou",
        country_code="BJ",
    ),
    "BL": Address(
        full_name="Test Recipient",
        address_line1="Rue de la République 1",
        city="Gustavia",
        postcode="97133",
        country_code="BL",
    ),
    "BM": Address(
        full_name="Test Recipient",
        address_line1="Front Street 1",
        city="Hamilton",
        postcode="HM 12",
        country_code="BM",
    ),
    "BN": Address(
        full_name="Test Recipient",
        address_line1="Jalan Sultan 1",
        city="Bandar Seri Begawan",
        postcode="BS8811",
        country_code="BN",
    ),
    "BO": Address(
        full_name="Test Recipient",
        address_line1="Plaza Murillo 1",
        city="La Paz",
        country_code="BO",
    ),
    "BQ": Address(
        full_name="Test Recipient",
        address_line1="Kaya Grandi 1",
        city="Kralendijk",
        country_code="BQ",
    ),
    "BR": Address(
        full_name="Test Recipient",
        address_line1="Avenida Paulista 1",
        city="São Paulo",
        postcode="01310-100",
        country_code="BR",
    ),
    "BS": Address(
        full_name="Test Recipient",
        address_line1="Bay Street 1",
        city="Nassau",
        country_code="BS",
    ),
    "BT": Address(
        full_name="Test Recipient",
        address_line1="Norzin Lam 1",
        city="Thimphu",
        postcode="11001",
        country_code="BT",
    ),
    "BV": Address(
        full_name="Test Recipient",
        address_line1="Bouvet Island",
        city="Bouvet Island",
        country_code="BV",
    ),
    "BW": Address(
        full_name="Test Recipient",
        address_line1="The Mall 1",
        city="Gaborone",
        country_code="BW",
    ),
    "BY": Address(
        full_name="Test Recipient",
        address_line1="Independence Avenue 1",
        city="Minsk",
        postcode="220004",
        country_code="BY",
    ),
    "BZ": Address(
        full_name="Test Recipient",
        address_line1="Regent Street 1",
        city="Belize City",
        country_code="BZ",
    ),
    "CA": Address(
        full_name="Test Recipient",
        address_line1="1 Sussex Drive",
        city="Ottawa",
        postcode="K1A 0A1",
        country_code="CA",
    ),
    "CC": Address(
        full_name="Test Recipient",
        address_line1="West Island Road 1",
        city="West Island",
        postcode="6799",
        country_code="CC",
    ),
    "CD": Address(
        full_name="Test Recipient",
        address_line1="Boulevard du 30 Juin 1",
        city="Kinshasa",
        country_code="CD",
    ),
    "CF": Address(
        full_name="Test Recipient",
        address_line1="Avenue de l'Indépendance 1",
        city="Bangui",
        country_code="CF",
    ),
    "CG": Address(
        full_name="Test Recipient",
        address_line1="Avenue Amilcar Cabral 1",
        city="Brazzaville",
        country_code="CG",
    ),
    "CH": Address(
        full_name="Test Recipient",
        address_line1="Bahnhofstrasse 1",
        city="Zurich",
        postcode="8001",
        country_code="CH",
    ),
    "CI": Address(
        full_name="Test Recipient",
        address_line1="Avenue Franchet d'Esperey 1",
        city="Abidjan",
        country_code="CI",
    ),
    "CK": Address(
        full_name="Test Recipient",
        address_line1="Takuvaine Road 1",
        city="Avarua",
        country_code="CK",
    ),
    "CL": Address(
        full_name="Test Recipient",
        address_line1="Avenida O'Higgins 1",
        city="Santiago",
        postcode="8320000",
        country_code="CL",
    ),
    "CM": Address(
        full_name="Test Recipient",
        address_line1="Avenue Ahmadou Ahidjo 1",
        city="Yaoundé",
        country_code="CM",
    ),
    "CN": Address(
        full_name="Test Recipient",
        address_line1="1 Chang'an Avenue",
        city="Beijing",
        postcode="100000",
        country_code="CN",
    ),
    "CO": Address(
        full_name="Test Recipient",
        address_line1="Carrera 7 No. 6-54",
        city="Bogotá",
        postcode="110111",
        country_code="CO",
    ),
    "CR": Address(
        full_name="Test Recipient",
        address_line1="Avenida Central 1",
        city="San José",
        postcode="10101",
        country_code="CR",
    ),
    "CU": Address(
        full_name="Test Recipient",
        address_line1="Calle Obispo 1",
        city="Havana",
        postcode="10100",
        country_code="CU",
    ),
    "CV": Address(
        full_name="Test Recipient",
        address_line1="Plateau 1",
        city="Praia",
        postcode="7600",
        country_code="CV",
    ),
    "CW": Address(
        full_name="Test Recipient",
        address_line1="Breedestraat 1",
        city="Willemstad",
        country_code="CW",
    ),
    "CX": Address(
        full_name="Test Recipient",
        address_line1="Flying Fish Cove Road 1",
        city="Flying Fish Cove",
        postcode="6798",
        country_code="CX",
    ),
    "CY": Address(
        full_name="Test Recipient",
        address_line1="Eleftherias Square 1",
        city="Nicosia",
        postcode="1016",
        country_code="CY",
    ),
    "CZ": Address(
        full_name="Test Recipient",
        address_line1="Václavské náměstí 1",
        city="Prague",
        postcode="110 00",
        country_code="CZ",
    ),
    "DE": Address(
        full_name="Test Empfänger",
        address_line1="Unter den Linden 1",
        city="Berlin",
        postcode="10117",
        country_code="DE",
    ),
    "DJ": Address(
        full_name="Test Recipient",
        address_line1="Place Lagarde 1",
        city="Djibouti",
        country_code="DJ",
    ),
    "DK": Address(
        full_name="Test Recipient",
        address_line1="Strøget 1",
        city="Copenhagen",
        postcode="1160",
        country_code="DK",
    ),
    "DM": Address(
        full_name="Test Recipient",
        address_line1="King George V Street 1",
        city="Roseau",
        country_code="DM",
    ),
    "DO": Address(
        full_name="Test Recipient",
        address_line1="Calle El Conde 1",
        city="Santo Domingo",
        postcode="10210",
        country_code="DO",
    ),
    "DZ": Address(
        full_name="Test Recipient",
        address_line1="1 Rue de la Casbah",
        city="Algiers",
        postcode="16000",
        country_code="DZ",
    ),
    "EC": Address(
        full_name="Test Recipient",
        address_line1="Avenida Amazonas 1",
        city="Quito",
        postcode="170501",
        country_code="EC",
    ),
    "EE": Address(
        full_name="Test Recipient",
        address_line1="Narva mnt 1",
        city="Tallinn",
        postcode="10143",
        country_code="EE",
    ),
    "EG": Address(
        full_name="Test Recipient",
        address_line1="El-Tahrir Square 1",
        city="Cairo",
        postcode="11511",
        country_code="EG",
    ),
    "EH": Address(
        full_name="Test Recipient",
        address_line1="Avenue Hassan II 1",
        city="El Aaiún",
        country_code="EH",
    ),
    "ER": Address(
        full_name="Test Recipient",
        address_line1="Harnet Avenue 1",
        city="Asmara",
        country_code="ER",
    ),
    "ES": Address(
        full_name="Test Recipient",
        address_line1="Calle de Alcalá 1",
        city="Madrid",
        postcode="28014",
        country_code="ES",
    ),
    "ET": Address(
        full_name="Test Recipient",
        address_line1="Churchill Avenue 1",
        city="Addis Ababa",
        postcode="1000",
        country_code="ET",
    ),
    "FI": Address(
        full_name="Test Recipient",
        address_line1="Mannerheimintie 1",
        city="Helsinki",
        postcode="00100",
        country_code="FI",
    ),
    "FJ": Address(
        full_name="Test Recipient",
        address_line1="Victoria Parade 1",
        city="Suva",
        country_code="FJ",
    ),
    "FK": Address(
        full_name="Test Recipient",
        address_line1="Ross Road 1",
        city="Stanley",
        postcode="FIQQ 1ZZ",
        country_code="FK",
    ),
    "FM": Address(
        full_name="Test Recipient",
        address_line1="Main Street 1",
        city="Palikir",
        postcode="96941",
        country_code="FM",
    ),
    "FO": Address(
        full_name="Test Recipient",
        address_line1="Tinganes 1",
        city="Tórshavn",
        postcode="100",
        country_code="FO",
    ),
    "FR": Address(
        full_name="Test Recipient",
        address_line1="1 Rue de Rivoli",
        city="Paris",
        postcode="75001",
        country_code="FR",
    ),
    "GA": Address(
        full_name="Test Recipient",
        address_line1="Boulevard Triomphal 1",
        city="Libreville",
        country_code="GA",
    ),
    "GB": Address(
        full_name="Test Recipient",
        address_line1="1 Test Street",
        city="London",
        postcode="SW1A 1AA",
        country_code="GB",
    ),
    "GD": Address(
        full_name="Test Recipient",
        address_line1="Carenage Street 1",
        city="St. George's",
        country_code="GD",
    ),
    "GE": Address(
        full_name="Test Recipient",
        address_line1="Rustaveli Avenue 1",
        city="Tbilisi",
        postcode="0108",
        country_code="GE",
    ),
    "GF": Address(
        full_name="Test Recipient",
        address_line1="Avenue du Général de Gaulle 1",
        city="Cayenne",
        postcode="97300",
        country_code="GF",
    ),
    "GG": Address(
        full_name="Test Recipient",
        address_line1="Market Street 1",
        city="St Peter Port",
        postcode="GY1 1AA",
        country_code="GG",
    ),
    "GH": Address(
        full_name="Test Recipient",
        address_line1="Kojo Thompson Road 1",
        city="Accra",
        country_code="GH",
    ),
    "GI": Address(
        full_name="Test Recipient",
        address_line1="Main Street 1",
        city="Gibraltar",
        postcode="GX11 1AA",
        country_code="GI",
    ),
    "GL": Address(
        full_name="Test Recipient",
        address_line1="Hans Egedesvej 1",
        city="Nuuk",
        postcode="3900",
        country_code="GL",
    ),
    "GM": Address(
        full_name="Test Recipient",
        address_line1="Independence Drive 1",
        city="Banjul",
        country_code="GM",
    ),
    "GN": Address(
        full_name="Test Recipient",
        address_line1="Avenue de la République 1",
        city="Conakry",
        country_code="GN",
    ),
    "GP": Address(
        full_name="Test Recipient",
        address_line1="Rue Frébault 1",
        city="Pointe-à-Pitre",
        postcode="97100",
        country_code="GP",
    ),
    "GQ": Address(
        full_name="Test Recipient",
        address_line1="Avenida de la Libertad 1",
        city="Malabo",
        country_code="GQ",
    ),
    "GR": Address(
        full_name="Test Recipient",
        address_line1="Syntagma Square 1",
        city="Athens",
        postcode="10563",
        country_code="GR",
    ),
    "GS": Address(
        full_name="Test Recipient",
        address_line1="King Edward Point 1",
        city="King Edward Point",
        postcode="SIQQ 1ZZ",
        country_code="GS",
    ),
    "GT": Address(
        full_name="Test Recipient",
        address_line1="6a Avenida 1",
        city="Guatemala City",
        postcode="01001",
        country_code="GT",
    ),
    "GU": Address(
        full_name="Test Recipient",
        address_line1="Marine Corps Drive 1",
        city="Hagåtña",
        postcode="96910",
        country_code="GU",
    ),
    "GW": Address(
        full_name="Test Recipient",
        address_line1="Avenida Amilcar Cabral 1",
        city="Bissau",
        country_code="GW",
    ),
    "GY": Address(
        full_name="Test Recipient",
        address_line1="Main Street 1",
        city="Georgetown",
        country_code="GY",
    ),
    "HK": Address(
        full_name="Test Recipient",
        address_line1="1 Connaught Place",
        city="Central",
        country_code="HK",
    ),
    "HM": Address(
        full_name="Test Recipient",
        address_line1="Atlas Cove 1",
        city="Atlas Cove",
        country_code="HM",
    ),
    "HN": Address(
        full_name="Test Recipient",
        address_line1="Avenida Los Proceres 1",
        city="Tegucigalpa",
        postcode="11101",
        country_code="HN",
    ),
    "HR": Address(
        full_name="Test Recipient",
        address_line1="Trg bana Jelačića 1",
        city="Zagreb",
        postcode="10000",
        country_code="HR",
    ),
    "HT": Address(
        full_name="Test Recipient",
        address_line1="Champs de Mars 1",
        city="Port-au-Prince",
        postcode="HT6110",
        country_code="HT",
    ),
    "HU": Address(
        full_name="Test Recipient",
        address_line1="Vörösmarty tér 1",
        city="Budapest",
        postcode="1051",
        country_code="HU",
    ),
    "ID": Address(
        full_name="Test Recipient",
        address_line1="Jalan Medan Merdeka Barat 1",
        city="Jakarta",
        postcode="10110",
        country_code="ID",
    ),
    "IE": Address(
        full_name="Test Recipient",
        address_line1="1 Merrion Square",
        city="Dublin",
        postcode="D02 HE97",
        country_code="IE",
    ),
    "IL": Address(
        full_name="Test Recipient",
        address_line1="Jaffa Street 1",
        city="Jerusalem",
        postcode="91010",
        country_code="IL",
    ),
    "IM": Address(
        full_name="Test Recipient",
        address_line1="Strand Street 1",
        city="Douglas",
        postcode="IM1 2AA",
        country_code="IM",
    ),
    "IN": Address(
        full_name="Test Recipient",
        address_line1="Connaught Place 1",
        city="New Delhi",
        postcode="110001",
        country_code="IN",
    ),
    "IO": Address(
        full_name="Test Recipient",
        address_line1="Diego Garcia 1",
        city="Diego Garcia",
        postcode="BBND 1ZZ",
        country_code="IO",
    ),
    "IQ": Address(
        full_name="Test Recipient",
        address_line1="Al-Rasheed Street 1",
        city="Baghdad",
        postcode="10001",
        country_code="IQ",
    ),
    "IR": Address(
        full_name="Test Recipient",
        address_line1="Vali-e-Asr Street 1",
        city="Tehran",
        postcode="1969763111",
        country_code="IR",
    ),
    "IS": Address(
        full_name="Test Recipient",
        address_line1="Lækjartorg 1",
        city="Reykjavik",
        postcode="101",
        country_code="IS",
    ),
    "IT": Address(
        full_name="Test Recipient",
        address_line1="Via del Corso 1",
        city="Rome",
        postcode="00186",
        country_code="IT",
    ),
    "JE": Address(
        full_name="Test Recipient",
        address_line1="King Street 1",
        city="St Helier",
        postcode="JE2 4AA",
        country_code="JE",
    ),
    "JM": Address(
        full_name="Test Recipient",
        address_line1="King Street 1",
        city="Kingston",
        country_code="JM",
    ),
    "JO": Address(
        full_name="Test Recipient",
        address_line1="Rainbow Street 1",
        city="Amman",
        postcode="11118",
        country_code="JO",
    ),
    "JP": Address(
        full_name="Test Recipient",
        address_line1="1-1 Chiyoda",
        city="Tokyo",
        postcode="100-0001",
        country_code="JP",
    ),
    "KE": Address(
        full_name="Test Recipient",
        address_line1="Kenyatta Avenue 1",
        city="Nairobi",
        postcode="00100",
        country_code="KE",
    ),
    "KG": Address(
        full_name="Test Recipient",
        address_line1="Chui Avenue 1",
        city="Bishkek",
        postcode="720001",
        country_code="KG",
    ),
    "KH": Address(
        full_name="Test Recipient",
        address_line1="Norodom Boulevard 1",
        city="Phnom Penh",
        postcode="12000",
        country_code="KH",
    ),
    "KI": Address(
        full_name="Test Recipient",
        address_line1="Bairiki Road 1",
        city="Tarawa",
        country_code="KI",
    ),
    "KM": Address(
        full_name="Test Recipient",
        address_line1="Boulevard de Strasbourg 1",
        city="Moroni",
        country_code="KM",
    ),
    "KN": Address(
        full_name="Test Recipient",
        address_line1="Central Street 1",
        city="Basseterre",
        country_code="KN",
    ),
    "KP": Address(
        full_name="Test Recipient",
        address_line1="Sungri Street 1",
        city="Pyongyang",
        country_code="KP",
    ),
    "KR": Address(
        full_name="Test Recipient",
        address_line1="Sejong-daero 1",
        city="Seoul",
        postcode="04524",
        country_code="KR",
    ),
    "KW": Address(
        full_name="Test Recipient",
        address_line1="Arabian Gulf Street 1",
        city="Kuwait City",
        postcode="13001",
        country_code="KW",
    ),
    "KY": Address(
        full_name="Test Recipient",
        address_line1="Elgin Avenue 1",
        city="George Town",
        postcode="KY1-9000",
        country_code="KY",
    ),
    "KZ": Address(
        full_name="Test Recipient",
        address_line1="Nursultan Avenue 1",
        city="Astana",
        postcode="010000",
        country_code="KZ",
    ),
    "LA": Address(
        full_name="Test Recipient",
        address_line1="Lane Xang Avenue 1",
        city="Vientiane",
        postcode="0100",
        country_code="LA",
    ),
    "LB": Address(
        full_name="Test Recipient",
        address_line1="Martyrs' Square 1",
        city="Beirut",
        country_code="LB",
    ),
    "LC": Address(
        full_name="Test Recipient",
        address_line1="Bridge Street 1",
        city="Castries",
        country_code="LC",
    ),
    "LI": Address(
        full_name="Test Recipient",
        address_line1="Städtle 1",
        city="Vaduz",
        postcode="9490",
        country_code="LI",
    ),
    "LK": Address(
        full_name="Test Recipient",
        address_line1="Galle Road 1",
        city="Colombo",
        postcode="00300",
        country_code="LK",
    ),
    "LR": Address(
        full_name="Test Recipient",
        address_line1="Broad Street 1",
        city="Monrovia",
        country_code="LR",
    ),
    "LS": Address(
        full_name="Test Recipient",
        address_line1="Kingsway 1",
        city="Maseru",
        postcode="100",
        country_code="LS",
    ),
    "LT": Address(
        full_name="Test Recipient",
        address_line1="Gedimino prospektas 1",
        city="Vilnius",
        postcode="01103",
        country_code="LT",
    ),
    "LU": Address(
        full_name="Test Recipient",
        address_line1="Grand-Rue 1",
        city="Luxembourg City",
        postcode="L-1660",
        country_code="LU",
    ),
    "LV": Address(
        full_name="Test Recipient",
        address_line1="Brīvības bulvāris 1",
        city="Riga",
        postcode="LV-1010",
        country_code="LV",
    ),
    "LY": Address(
        full_name="Test Recipient",
        address_line1="Omar Mukhtar Street 1",
        city="Tripoli",
        country_code="LY",
    ),
    "MA": Address(
        full_name="Test Recipient",
        address_line1="Avenue Mohammed V 1",
        city="Rabat",
        postcode="10000",
        country_code="MA",
    ),
    "MC": Address(
        full_name="Test Recipient",
        address_line1="Avenue des Beaux-Arts 1",
        city="Monaco",
        postcode="98000",
        country_code="MC",
    ),
    "MD": Address(
        full_name="Test Recipient",
        address_line1="Strada Ștefan cel Mare 1",
        city="Chișinău",
        postcode="MD-2001",
        country_code="MD",
    ),
    "ME": Address(
        full_name="Test Recipient",
        address_line1="Cetinjska 1",
        city="Podgorica",
        postcode="81000",
        country_code="ME",
    ),
    "MF": Address(
        full_name="Test Recipient",
        address_line1="Route de Sandy Ground 1",
        city="Marigot",
        postcode="97150",
        country_code="MF",
    ),
    "MG": Address(
        full_name="Test Recipient",
        address_line1="Avenue de l'Indépendance 1",
        city="Antananarivo",
        postcode="101",
        country_code="MG",
    ),
    "MH": Address(
        full_name="Test Recipient",
        address_line1="Lagoon Road 1",
        city="Majuro",
        postcode="96960",
        country_code="MH",
    ),
    "MK": Address(
        full_name="Test Recipient",
        address_line1="Macedonia Square 1",
        city="Skopje",
        postcode="1000",
        country_code="MK",
    ),
    "ML": Address(
        full_name="Test Recipient",
        address_line1="Avenue de la Liberté 1",
        city="Bamako",
        country_code="ML",
    ),
    "MM": Address(
        full_name="Test Recipient",
        address_line1="Naypyidaw Road 1",
        city="Naypyidaw",
        postcode="15011",
        country_code="MM",
    ),
    "MN": Address(
        full_name="Test Recipient",
        address_line1="Sukhbaatar Square 1",
        city="Ulaanbaatar",
        postcode="14200",
        country_code="MN",
    ),
    "MO": Address(
        full_name="Test Recipient",
        address_line1="Largo do Senado 1",
        city="Macau",
        country_code="MO",
    ),
    "MP": Address(
        full_name="Test Recipient",
        address_line1="Beach Road 1",
        city="Saipan",
        postcode="96950",
        country_code="MP",
    ),
    "MQ": Address(
        full_name="Test Recipient",
        address_line1="Rue Victor Hugo 1",
        city="Fort-de-France",
        postcode="97200",
        country_code="MQ",
    ),
    "MR": Address(
        full_name="Test Recipient",
        address_line1="Avenue du Roi Faisal 1",
        city="Nouakchott",
        country_code="MR",
    ),
    "MS": Address(
        full_name="Test Recipient",
        address_line1="Main Street 1",
        city="Brades",
        country_code="MS",
    ),
    "MT": Address(
        full_name="Test Recipient",
        address_line1="Republic Street 1",
        city="Valletta",
        postcode="VLT 1110",
        country_code="MT",
    ),
    "MU": Address(
        full_name="Test Recipient",
        address_line1="Royal Road 1",
        city="Port Louis",
        postcode="11302",
        country_code="MU",
    ),
    "MV": Address(
        full_name="Test Recipient",
        address_line1="Orchid Magu 1",
        city="Malé",
        postcode="20026",
        country_code="MV",
    ),
    "MW": Address(
        full_name="Test Recipient",
        address_line1="Independence Drive 1",
        city="Lilongwe",
        country_code="MW",
    ),
    "MX": Address(
        full_name="Test Recipient",
        address_line1="Avenida Madero 1",
        city="Mexico City",
        postcode="06000",
        country_code="MX",
    ),
    "MY": Address(
        full_name="Test Recipient",
        address_line1="Jalan Tuanku Abdul Halim 1",
        city="Kuala Lumpur",
        postcode="50480",
        country_code="MY",
    ),
    "MZ": Address(
        full_name="Test Recipient",
        address_line1="Avenida Julius Nyerere 1",
        city="Maputo",
        country_code="MZ",
    ),
    "NA": Address(
        full_name="Test Recipient",
        address_line1="Independence Avenue 1",
        city="Windhoek",
        postcode="9000",
        country_code="NA",
    ),
    "NC": Address(
        full_name="Test Recipient",
        address_line1="Route Nationale 1",
        city="Nouméa",
        postcode="98800",
        country_code="NC",
    ),
    "NE": Address(
        full_name="Test Recipient",
        address_line1="Avenue du Général de Gaulle 1",
        city="Niamey",
        country_code="NE",
    ),
    "NF": Address(
        full_name="Test Recipient",
        address_line1="New Cascade Road 1",
        city="Kingston",
        postcode="2899",
        country_code="NF",
    ),
    "NG": Address(
        full_name="Test Recipient",
        address_line1="Herbert Macaulay Way 1",
        city="Abuja",
        postcode="900001",
        country_code="NG",
    ),
    "NI": Address(
        full_name="Test Recipient",
        address_line1="Avenida Central 1",
        city="Managua",
        postcode="14038",
        country_code="NI",
    ),
    "NL": Address(
        full_name="Test Recipient",
        address_line1="Dam 1",
        city="Amsterdam",
        postcode="1012 JS",
        country_code="NL",
    ),
    "NO": Address(
        full_name="Test Recipient",
        address_line1="Karl Johans gate 1",
        city="Oslo",
        postcode="0154",
        country_code="NO",
    ),
    "NP": Address(
        full_name="Test Recipient",
        address_line1="Durbar Marg 1",
        city="Kathmandu",
        postcode="44600",
        country_code="NP",
    ),
    "NR": Address(
        full_name="Test Recipient",
        address_line1="Civic Centre Road 1",
        city="Yaren",
        country_code="NR",
    ),
    "NU": Address(
        full_name="Test Recipient",
        address_line1="Fonuakula Road 1",
        city="Alofi",
        country_code="NU",
    ),
    "NZ": Address(
        full_name="Test Recipient",
        address_line1="1 Lambton Quay",
        city="Wellington",
        postcode="6011",
        country_code="NZ",
    ),
    "OM": Address(
        full_name="Test Recipient",
        address_line1="Muttrah Corniche 1",
        city="Muscat",
        postcode="112",
        country_code="OM",
    ),
    "PA": Address(
        full_name="Test Recipient",
        address_line1="Avenida Central 1",
        city="Panama City",
        postcode="0816",
        country_code="PA",
    ),
    "PE": Address(
        full_name="Test Recipient",
        address_line1="Jirón de la Unión 1",
        city="Lima",
        postcode="15001",
        country_code="PE",
    ),
    "PF": Address(
        full_name="Test Recipient",
        address_line1="Boulevard Pomare 1",
        city="Papeete",
        postcode="98713",
        country_code="PF",
    ),
    "PG": Address(
        full_name="Test Recipient",
        address_line1="Waigani Drive 1",
        city="Port Moresby",
        postcode="121",
        country_code="PG",
    ),
    "PH": Address(
        full_name="Test Recipient",
        address_line1="Roxas Boulevard 1",
        city="Manila",
        postcode="1000",
        country_code="PH",
    ),
    "PK": Address(
        full_name="Test Recipient",
        address_line1="Constitution Avenue 1",
        city="Islamabad",
        postcode="44000",
        country_code="PK",
    ),
    "PL": Address(
        full_name="Test Recipient",
        address_line1="Nowy Świat 1",
        city="Warsaw",
        postcode="00-001",
        country_code="PL",
    ),
    "PM": Address(
        full_name="Test Recipient",
        address_line1="Rue du Lieutenant Colonel Pigeaud 1",
        city="Saint-Pierre",
        postcode="97500",
        country_code="PM",
    ),
    "PN": Address(
        full_name="Test Recipient",
        address_line1="Adamstown Road 1",
        city="Adamstown",
        postcode="PCRN 1ZZ",
        country_code="PN",
    ),
    "PR": Address(
        full_name="Test Recipient",
        address_line1="Calle Fortaleza 1",
        city="San Juan",
        postcode="00901",
        country_code="PR",
    ),
    "PS": Address(
        full_name="Test Recipient",
        address_line1="Al-Manara Square 1",
        city="Ramallah",
        country_code="PS",
    ),
    "PT": Address(
        full_name="Test Recipient",
        address_line1="Avenida da Liberdade 1",
        city="Lisbon",
        postcode="1250-096",
        country_code="PT",
    ),
    "PW": Address(
        full_name="Test Recipient",
        address_line1="Ngerulmud Road 1",
        city="Ngerulmud",
        postcode="96940",
        country_code="PW",
    ),
    "PY": Address(
        full_name="Test Recipient",
        address_line1="Avenida Mariscal López 1",
        city="Asunción",
        postcode="1209",
        country_code="PY",
    ),
    "QA": Address(
        full_name="Test Recipient",
        address_line1="Corniche Road 1",
        city="Doha",
        postcode="00973",
        country_code="QA",
    ),
    "RE": Address(
        full_name="Test Recipient",
        address_line1="Rue Jules Auber 1",
        city="Saint-Denis",
        postcode="97400",
        country_code="RE",
    ),
    "RO": Address(
        full_name="Test Recipient",
        address_line1="Bulevardul Unirii 1",
        city="Bucharest",
        postcode="030167",
        country_code="RO",
    ),
    "RS": Address(
        full_name="Test Recipient",
        address_line1="Knez Mihailova 1",
        city="Belgrade",
        postcode="11000",
        country_code="RS",
    ),
    "RU": Address(
        full_name="Test Recipient",
        address_line1="Red Square 1",
        city="Moscow",
        postcode="109012",
        country_code="RU",
    ),
    "RW": Address(
        full_name="Test Recipient",
        address_line1="KN 3 Ave 1",
        city="Kigali",
        postcode="00000",
        country_code="RW",
    ),
    "SA": Address(
        full_name="Test Recipient",
        address_line1="King Fahd Road 1",
        city="Riyadh",
        postcode="11564",
        country_code="SA",
    ),
    "SB": Address(
        full_name="Test Recipient",
        address_line1="Mendana Avenue 1",
        city="Honiara",
        country_code="SB",
    ),
    "SC": Address(
        full_name="Test Recipient",
        address_line1="Francis Rachel Street 1",
        city="Victoria",
        country_code="SC",
    ),
    "SD": Address(
        full_name="Test Recipient",
        address_line1="El Neel Avenue 1",
        city="Khartoum",
        postcode="11111",
        country_code="SD",
    ),
    "SE": Address(
        full_name="Test Recipient",
        address_line1="Drottninggatan 1",
        city="Stockholm",
        postcode="111 51",
        country_code="SE",
    ),
    "SG": Address(
        full_name="Test Recipient",
        address_line1="1 Orchard Road",
        city="Singapore",
        postcode="238801",
        country_code="SG",
    ),
    "SH": Address(
        full_name="Test Recipient",
        address_line1="Main Street 1",
        city="Jamestown",
        postcode="STHL 1ZZ",
        country_code="SH",
    ),
    "SI": Address(
        full_name="Test Recipient",
        address_line1="Prešernov trg 1",
        city="Ljubljana",
        postcode="1000",
        country_code="SI",
    ),
    "SJ": Address(
        full_name="Test Recipient",
        address_line1="Lompenveien 1",
        city="Longyearbyen",
        postcode="9170",
        country_code="SJ",
    ),
    "SK": Address(
        full_name="Test Recipient",
        address_line1="Námestie SNP 1",
        city="Bratislava",
        postcode="811 01",
        country_code="SK",
    ),
    "SL": Address(
        full_name="Test Recipient",
        address_line1="Siaka Stevens Street 1",
        city="Freetown",
        country_code="SL",
    ),
    "SM": Address(
        full_name="Test Recipient",
        address_line1="Contrada del Collegio 1",
        city="San Marino",
        postcode="47890",
        country_code="SM",
    ),
    "SN": Address(
        full_name="Test Recipient",
        address_line1="Avenue Léopold Sédar Senghor 1",
        city="Dakar",
        postcode="12500",
        country_code="SN",
    ),
    "SO": Address(
        full_name="Test Recipient",
        address_line1="Maka Al-Mukarama Road 1",
        city="Mogadishu",
        country_code="SO",
    ),
    "SR": Address(
        full_name="Test Recipient",
        address_line1="Keizerstraat 1",
        city="Paramaribo",
        country_code="SR",
    ),
    "SS": Address(
        full_name="Test Recipient",
        address_line1="Airport Road 1",
        city="Juba",
        country_code="SS",
    ),
    "ST": Address(
        full_name="Test Recipient",
        address_line1="Avenida da Independência 1",
        city="São Tomé",
        country_code="ST",
    ),
    "SV": Address(
        full_name="Test Recipient",
        address_line1="1a Calle Poniente 1",
        city="San Salvador",
        postcode="1101",
        country_code="SV",
    ),
    "SX": Address(
        full_name="Test Recipient",
        address_line1="W.J.A. Nisbeth Road 1",
        city="Philipsburg",
        country_code="SX",
    ),
    "SY": Address(
        full_name="Test Recipient",
        address_line1="Martyrs' Square 1",
        city="Damascus",
        country_code="SY",
    ),
    "SZ": Address(
        full_name="Test Recipient",
        address_line1="Msakato Street 1",
        city="Mbabane",
        postcode="H100",
        country_code="SZ",
    ),
    "TC": Address(
        full_name="Test Recipient",
        address_line1="Front Street 1",
        city="Grand Turk",
        postcode="TKCA 1ZZ",
        country_code="TC",
    ),
    "TD": Address(
        full_name="Test Recipient",
        address_line1="Avenue Charles de Gaulle 1",
        city="N'Djamena",
        country_code="TD",
    ),
    "TF": Address(
        full_name="Test Recipient",
        address_line1="Port-aux-Français 1",
        city="Port-aux-Français",
        country_code="TF",
    ),
    "TG": Address(
        full_name="Test Recipient",
        address_line1="Avenue Nicolas Grunitzky 1",
        city="Lomé",
        country_code="TG",
    ),
    "TH": Address(
        full_name="Test Recipient",
        address_line1="Thanon Ratchadamnoen 1",
        city="Bangkok",
        postcode="10200",
        country_code="TH",
    ),
    "TJ": Address(
        full_name="Test Recipient",
        address_line1="Rudaki Avenue 1",
        city="Dushanbe",
        postcode="734001",
        country_code="TJ",
    ),
    "TK": Address(
        full_name="Test Recipient",
        address_line1="Fakaofo Road 1",
        city="Fakaofo",
        country_code="TK",
    ),
    "TL": Address(
        full_name="Test Recipient",
        address_line1="Avenida Marginal Bidau 1",
        city="Dili",
        country_code="TL",
    ),
    "TM": Address(
        full_name="Test Recipient",
        address_line1="Archabil Shayoly 1",
        city="Ashgabat",
        postcode="744000",
        country_code="TM",
    ),
    "TN": Address(
        full_name="Test Recipient",
        address_line1="Avenue Habib Bourguiba 1",
        city="Tunis",
        postcode="1001",
        country_code="TN",
    ),
    "TO": Address(
        full_name="Test Recipient",
        address_line1="Taufa'ahau Road 1",
        city="Nukuʻalofa",
        country_code="TO",
    ),
    "TR": Address(
        full_name="Test Recipient",
        address_line1="Atatürk Bulvarı 1",
        city="Ankara",
        postcode="06100",
        country_code="TR",
    ),
    "TT": Address(
        full_name="Test Recipient",
        address_line1="Frederick Street 1",
        city="Port of Spain",
        country_code="TT",
    ),
    "TV": Address(
        full_name="Test Recipient",
        address_line1="Vaiaku Road 1",
        city="Funafuti",
        country_code="TV",
    ),
    "TW": Address(
        full_name="Test Recipient",
        address_line1="Zhongshan North Road 1",
        city="Taipei",
        postcode="10452",
        country_code="TW",
    ),
    "TZ": Address(
        full_name="Test Recipient",
        address_line1="Samora Avenue 1",
        city="Dar es Salaam",
        postcode="11101",
        country_code="TZ",
    ),
    "UA": Address(
        full_name="Test Recipient",
        address_line1="Khreshchatyk Street 1",
        city="Kyiv",
        postcode="01001",
        country_code="UA",
    ),
    "UG": Address(
        full_name="Test Recipient",
        address_line1="Kampala Road 1",
        city="Kampala",
        country_code="UG",
    ),
    "UM": Address(
        full_name="Test Recipient",
        address_line1="Johnston Atoll 1",
        city="Johnston Atoll",
        country_code="UM",
    ),
    "US": Address(
        full_name="Test Recipient",
        address_line1="1600 Pennsylvania Avenue NW",
        city="Washington DC",
        postcode="20500",
        country_code="US",
    ),
    "UY": Address(
        full_name="Test Recipient",
        address_line1="18 de Julio Avenue 1",
        city="Montevideo",
        postcode="11100",
        country_code="UY",
    ),
    "UZ": Address(
        full_name="Test Recipient",
        address_line1="Amir Timur Street 1",
        city="Tashkent",
        postcode="100029",
        country_code="UZ",
    ),
    "VA": Address(
        full_name="Test Recipient",
        address_line1="Piazza San Pietro 1",
        city="Vatican City",
        postcode="00120",
        country_code="VA",
    ),
    "VC": Address(
        full_name="Test Recipient",
        address_line1="Bay Street 1",
        city="Kingstown",
        country_code="VC",
    ),
    "VE": Address(
        full_name="Test Recipient",
        address_line1="Avenida Urdaneta 1",
        city="Caracas",
        postcode="1010",
        country_code="VE",
    ),
    "VG": Address(
        full_name="Test Recipient",
        address_line1="Main Street 1",
        city="Road Town",
        country_code="VG",
    ),
    "VI": Address(
        full_name="Test Recipient",
        address_line1="Veterans Drive 1",
        city="Charlotte Amalie",
        postcode="00802",
        country_code="VI",
    ),
    "VN": Address(
        full_name="Test Recipient",
        address_line1="1 Dinh Tien Hoang",
        city="Hanoi",
        postcode="10000",
        country_code="VN",
    ),
    "VU": Address(
        full_name="Test Recipient",
        address_line1="Kumul Highway 1",
        city="Port Vila",
        country_code="VU",
    ),
    "WF": Address(
        full_name="Test Recipient",
        address_line1="Rue du Général de Gaulle 1",
        city="Mata-Utu",
        postcode="98600",
        country_code="WF",
    ),
    "WS": Address(
        full_name="Test Recipient",
        address_line1="Beach Road 1",
        city="Apia",
        country_code="WS",
    ),
    "YE": Address(
        full_name="Test Recipient",
        address_line1="Al-Zubairi Street 1",
        city="Sanaa",
        country_code="YE",
    ),
    "YT": Address(
        full_name="Test Recipient",
        address_line1="Rue du Commerce 1",
        city="Mamoudzou",
        postcode="97600",
        country_code="YT",
    ),
    "ZA": Address(
        full_name="Test Recipient",
        address_line1="1 Parliament Street",
        city="Cape Town",
        postcode="8001",
        country_code="ZA",
    ),
    "ZM": Address(
        full_name="Test Recipient",
        address_line1="Cairo Road 1",
        city="Lusaka",
        postcode="10101",
        country_code="ZM",
    ),
    "ZW": Address(
        full_name="Test Recipient",
        address_line1="Samora Machel Avenue 1",
        city="Harare",
        country_code="ZW",
    ),
}

__all__ = ["ADDRESSES", "get_address", "get_all_country_codes"]
