# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Address(BaseModel):
    """
    Address
    """ # noqa: E501
    title: Optional[Annotated[str, Field(strict=True, max_length=25)]] = None
    first_name: Annotated[str, Field(strict=True, max_length=150)] = Field(alias="firstName")
    last_name: Annotated[str, Field(strict=True, max_length=150)] = Field(alias="lastName")
    company_name: Optional[Annotated[str, Field(strict=True, max_length=250)]] = Field(default=None, alias="companyName")
    address_line1: Annotated[str, Field(strict=True, max_length=250)] = Field(alias="addressLine1")
    address_line2: Optional[Annotated[str, Field(strict=True, max_length=250)]] = Field(default=None, alias="addressLine2")
    address_line3: Optional[Annotated[str, Field(strict=True, max_length=250)]] = Field(default=None, alias="addressLine3")
    city: Annotated[str, Field(strict=True, max_length=100)]
    county: Optional[Annotated[str, Field(strict=True, max_length=250)]] = None
    postcode: Annotated[str, Field(strict=True, max_length=25)]
    country: Annotated[str, Field(strict=True, max_length=50)]
    country_iso_code: Annotated[str, Field(strict=True, max_length=3)] = Field(description="ISO 3166-1 alpha-3 country code (e.g. GBR, USA)", alias="countryIsoCode")
    __properties: ClassVar[List[str]] = ["title", "firstName", "lastName", "companyName", "addressLine1", "addressLine2", "addressLine3", "city", "county", "postcode", "country", "countryIsoCode"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Address from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Address from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "companyName": obj.get("companyName"),
            "addressLine1": obj.get("addressLine1"),
            "addressLine2": obj.get("addressLine2"),
            "addressLine3": obj.get("addressLine3"),
            "city": obj.get("city"),
            "county": obj.get("county"),
            "postcode": obj.get("postcode"),
            "country": obj.get("country"),
            "countryIsoCode": obj.get("countryIsoCode")
        })
        return _obj


