# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, constr

class AddressRequest(BaseModel):
    """
    AddressRequest
    """
    full_name: Optional[constr(strict=True, max_length=210)] = Field(default=None, alias="fullName")
    company_name: Optional[constr(strict=True, max_length=100)] = Field(default=None, alias="companyName")
    address_line1: constr(strict=True, max_length=100) = Field(default=..., alias="addressLine1")
    address_line2: Optional[constr(strict=True, max_length=100)] = Field(default=None, alias="addressLine2")
    address_line3: Optional[constr(strict=True, max_length=100)] = Field(default=None, alias="addressLine3")
    city: constr(strict=True, max_length=100) = Field(...)
    county: Optional[constr(strict=True, max_length=100)] = None
    postcode: Optional[constr(strict=True, max_length=20)] = None
    country_code: constr(strict=True, max_length=3) = Field(default=..., alias="countryCode")
    __properties = ["fullName", "companyName", "addressLine1", "addressLine2", "addressLine3", "city", "county", "postcode", "countryCode"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AddressRequest:
        """Create an instance of AddressRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AddressRequest:
        """Create an instance of AddressRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AddressRequest.parse_obj(obj)

        _obj = AddressRequest.parse_obj({
            "full_name": obj.get("fullName"),
            "company_name": obj.get("companyName"),
            "address_line1": obj.get("addressLine1"),
            "address_line2": obj.get("addressLine2"),
            "address_line3": obj.get("addressLine3"),
            "city": obj.get("city"),
            "county": obj.get("county"),
            "postcode": obj.get("postcode"),
            "country_code": obj.get("countryCode")
        })
        return _obj


