# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, constr
from click_and_drop_api.models.address_request import AddressRequest

class BillingDetailsRequest(BaseModel):
    """
    <b>Billing</b> along with <b>billing.address</b> objects are required in specific case when 'Use shipping address for billing address' setting is set to 'false' and 'Recipient.AddressBookReference' is provided.  # noqa: E501
    """
    address: Optional[AddressRequest] = None
    phone_number: Optional[constr(strict=True, max_length=25)] = Field(default=None, alias="phoneNumber")
    email_address: Optional[constr(strict=True, max_length=254)] = Field(default=None, alias="emailAddress")
    __properties = ["address", "phoneNumber", "emailAddress"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BillingDetailsRequest:
        """Create an instance of BillingDetailsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BillingDetailsRequest:
        """Create an instance of BillingDetailsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BillingDetailsRequest.parse_obj(obj)

        _obj = BillingDetailsRequest.parse_obj({
            "address": AddressRequest.from_dict(obj.get("address")) if obj.get("address") is not None else None,
            "phone_number": obj.get("phoneNumber"),
            "email_address": obj.get("emailAddress")
        })
        return _obj


