# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from click_and_drop_api.models.order_field_response import OrderFieldResponse

class CreateOrderErrorResponse(BaseModel):
    """
    CreateOrderErrorResponse
    """
    error_code: Optional[StrictInt] = Field(default=None, alias="errorCode")
    error_message: Optional[StrictStr] = Field(default=None, alias="errorMessage")
    fields: Optional[conlist(OrderFieldResponse)] = None
    __properties = ["errorCode", "errorMessage", "fields"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateOrderErrorResponse:
        """Create an instance of CreateOrderErrorResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list)
        _items = []
        if self.fields:
            for _item in self.fields:
                if _item:
                    _items.append(_item.to_dict())
            _dict['fields'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateOrderErrorResponse:
        """Create an instance of CreateOrderErrorResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateOrderErrorResponse.parse_obj(obj)

        _obj = CreateOrderErrorResponse.parse_obj({
            "error_code": obj.get("errorCode"),
            "error_message": obj.get("errorMessage"),
            "fields": [OrderFieldResponse.from_dict(_item) for _item in obj.get("fields")] if obj.get("fields") is not None else None
        })
        return _obj


