# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, conlist
from click_and_drop_api.models.create_order_response import CreateOrderResponse
from click_and_drop_api.models.failed_order_response import FailedOrderResponse

class CreateOrdersResponse(BaseModel):
    """
    CreateOrdersResponse
    """
    success_count: Optional[StrictInt] = Field(default=None, alias="successCount")
    errors_count: Optional[StrictInt] = Field(default=None, alias="errorsCount")
    created_orders: Optional[conlist(CreateOrderResponse)] = Field(default=None, alias="createdOrders")
    failed_orders: Optional[conlist(FailedOrderResponse)] = Field(default=None, alias="failedOrders")
    __properties = ["successCount", "errorsCount", "createdOrders", "failedOrders"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateOrdersResponse:
        """Create an instance of CreateOrdersResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in created_orders (list)
        _items = []
        if self.created_orders:
            for _item in self.created_orders:
                if _item:
                    _items.append(_item.to_dict())
            _dict['createdOrders'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in failed_orders (list)
        _items = []
        if self.failed_orders:
            for _item in self.failed_orders:
                if _item:
                    _items.append(_item.to_dict())
            _dict['failedOrders'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateOrdersResponse:
        """Create an instance of CreateOrdersResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateOrdersResponse.parse_obj(obj)

        _obj = CreateOrdersResponse.parse_obj({
            "success_count": obj.get("successCount"),
            "errors_count": obj.get("errorsCount"),
            "created_orders": [CreateOrderResponse.from_dict(_item) for _item in obj.get("createdOrders")] if obj.get("createdOrders") is not None else None,
            "failed_orders": [FailedOrderResponse.from_dict(_item) for _item in obj.get("failedOrders")] if obj.get("failedOrders") is not None else None
        })
        return _obj


