# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, confloat, conint, conlist, constr
from click_and_drop_api.models.billing_details_request import BillingDetailsRequest
from click_and_drop_api.models.importer import Importer
from click_and_drop_api.models.label_generation_request import LabelGenerationRequest
from click_and_drop_api.models.postage_details_request import PostageDetailsRequest
from click_and_drop_api.models.recipient_details_request import RecipientDetailsRequest
from click_and_drop_api.models.sender_details_request import SenderDetailsRequest
from click_and_drop_api.models.shipment_package_request import ShipmentPackageRequest
from click_and_drop_api.models.tag_request import TagRequest

class CreateOrderRequest(BaseModel):
    """
    CreateOrderRequest
    """
    order_reference: Optional[constr(strict=True, max_length=40)] = Field(default=None, alias="orderReference")
    is_recipient_a_business: Optional[StrictBool] = Field(default=None, alias="isRecipientABusiness", description="Indicates if the recipient is a business or not. Mandatory for Business senders on orders shipping from Great Britain to Northern Ireland, which require additional information for B2B shipments. (Business senders are OBA accounts and OLP accounts declaring themselves as a Business sender).")
    recipient: RecipientDetailsRequest = Field(...)
    sender: Optional[SenderDetailsRequest] = None
    billing: Optional[BillingDetailsRequest] = None
    packages: Optional[conlist(ShipmentPackageRequest)] = None
    order_date: datetime = Field(default=..., alias="orderDate")
    planned_despatch_date: Optional[datetime] = Field(default=None, alias="plannedDespatchDate")
    special_instructions: Optional[constr(strict=True, max_length=500)] = Field(default=None, alias="specialInstructions")
    subtotal: Union[confloat(le=999999, ge=0, multiple_of=0.01, strict=True), conint(le=999999, ge=0, strict=True)] = Field(default=..., description="The total value of all the goods in the order, excluding tax. This should not include retail shipping costs")
    shipping_cost_charged: Union[confloat(le=999999, ge=0, multiple_of=0.01, strict=True), conint(le=999999, ge=0, strict=True)] = Field(default=..., alias="shippingCostCharged", description="The shipping costs you charged to your customer")
    other_costs: Optional[Union[confloat(le=999999, ge=0, multiple_of=0.01, strict=True), conint(le=999999, ge=0, strict=True)]] = Field(default=None, alias="otherCosts")
    customs_duty_costs: Optional[Union[confloat(le=99999.99, ge=0, multiple_of=0.01, strict=True), conint(le=99999, ge=0, strict=True)]] = Field(default=None, alias="customsDutyCosts", description="Customs Duty Costs is only supported in DDP (Delivery Duty Paid) services")
    total: Union[confloat(le=999999, ge=0, multiple_of=0.01, strict=True), conint(le=999999, ge=0, strict=True)] = Field(default=..., description="The sum of order subtotal, tax and retail shipping costs")
    currency_code: Optional[constr(strict=True, max_length=3)] = Field(default=None, alias="currencyCode")
    postage_details: Optional[PostageDetailsRequest] = Field(default=None, alias="postageDetails")
    tags: Optional[conlist(TagRequest)] = None
    label: Optional[LabelGenerationRequest] = None
    order_tax: Optional[Union[confloat(le=999999, ge=0, multiple_of=0.01, strict=True), conint(le=999999, ge=0, strict=True)]] = Field(default=None, alias="orderTax", description="The total tax charged for the order")
    contains_dangerous_goods: Optional[StrictBool] = Field(default=None, alias="containsDangerousGoods", description="Indicates that the package contents contain a dangerous goods item")
    dangerous_goods_un_code: Optional[constr(strict=True, max_length=4)] = Field(default=None, alias="dangerousGoodsUnCode", description="UN Code of the dangerous goods")
    dangerous_goods_description: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="dangerousGoodsDescription", description="Description of the dangerous goods")
    dangerous_goods_quantity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="dangerousGoodsQuantity", description="Quantity or volume of the dangerous goods")
    importer: Optional[Importer] = None
    __properties = ["orderReference", "isRecipientABusiness", "recipient", "sender", "billing", "packages", "orderDate", "plannedDespatchDate", "specialInstructions", "subtotal", "shippingCostCharged", "otherCosts", "customsDutyCosts", "total", "currencyCode", "postageDetails", "tags", "label", "orderTax", "containsDangerousGoods", "dangerousGoodsUnCode", "dangerousGoodsDescription", "dangerousGoodsQuantity", "importer"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateOrderRequest:
        """Create an instance of CreateOrderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of recipient
        if self.recipient:
            _dict['recipient'] = self.recipient.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sender
        if self.sender:
            _dict['sender'] = self.sender.to_dict()
        # override the default output from pydantic by calling `to_dict()` of billing
        if self.billing:
            _dict['billing'] = self.billing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in packages (list)
        _items = []
        if self.packages:
            for _item in self.packages:
                if _item:
                    _items.append(_item.to_dict())
            _dict['packages'] = _items
        # override the default output from pydantic by calling `to_dict()` of postage_details
        if self.postage_details:
            _dict['postageDetails'] = self.postage_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of label
        if self.label:
            _dict['label'] = self.label.to_dict()
        # override the default output from pydantic by calling `to_dict()` of importer
        if self.importer:
            _dict['importer'] = self.importer.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateOrderRequest:
        """Create an instance of CreateOrderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateOrderRequest.parse_obj(obj)

        _obj = CreateOrderRequest.parse_obj({
            "order_reference": obj.get("orderReference"),
            "is_recipient_a_business": obj.get("isRecipientABusiness"),
            "recipient": RecipientDetailsRequest.from_dict(obj.get("recipient")) if obj.get("recipient") is not None else None,
            "sender": SenderDetailsRequest.from_dict(obj.get("sender")) if obj.get("sender") is not None else None,
            "billing": BillingDetailsRequest.from_dict(obj.get("billing")) if obj.get("billing") is not None else None,
            "packages": [ShipmentPackageRequest.from_dict(_item) for _item in obj.get("packages")] if obj.get("packages") is not None else None,
            "order_date": obj.get("orderDate"),
            "planned_despatch_date": obj.get("plannedDespatchDate"),
            "special_instructions": obj.get("specialInstructions"),
            "subtotal": obj.get("subtotal"),
            "shipping_cost_charged": obj.get("shippingCostCharged"),
            "other_costs": obj.get("otherCosts"),
            "customs_duty_costs": obj.get("customsDutyCosts"),
            "total": obj.get("total"),
            "currency_code": obj.get("currencyCode"),
            "postage_details": PostageDetailsRequest.from_dict(obj.get("postageDetails")) if obj.get("postageDetails") is not None else None,
            "tags": [TagRequest.from_dict(_item) for _item in obj.get("tags")] if obj.get("tags") is not None else None,
            "label": LabelGenerationRequest.from_dict(obj.get("label")) if obj.get("label") is not None else None,
            "order_tax": obj.get("orderTax"),
            "contains_dangerous_goods": obj.get("containsDangerousGoods"),
            "dangerous_goods_un_code": obj.get("dangerousGoodsUnCode"),
            "dangerous_goods_description": obj.get("dangerousGoodsDescription"),
            "dangerous_goods_quantity": obj.get("dangerousGoodsQuantity"),
            "importer": Importer.from_dict(obj.get("importer")) if obj.get("importer") is not None else None
        })
        return _obj


