# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, conlist
from click_and_drop_api.models.deleted_order_info import DeletedOrderInfo
from click_and_drop_api.models.order_error_info import OrderErrorInfo

class DeleteOrdersResource(BaseModel):
    """
    DeleteOrdersResource
    """
    deleted_orders: Optional[conlist(DeletedOrderInfo)] = Field(default=None, alias="deletedOrders")
    errors: Optional[conlist(OrderErrorInfo)] = None
    __properties = ["deletedOrders", "errors"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DeleteOrdersResource:
        """Create an instance of DeleteOrdersResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in deleted_orders (list)
        _items = []
        if self.deleted_orders:
            for _item in self.deleted_orders:
                if _item:
                    _items.append(_item.to_dict())
            _dict['deletedOrders'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in errors (list)
        _items = []
        if self.errors:
            for _item in self.errors:
                if _item:
                    _items.append(_item.to_dict())
            _dict['errors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DeleteOrdersResource:
        """Create an instance of DeleteOrdersResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DeleteOrdersResource.parse_obj(obj)

        _obj = DeleteOrdersResource.parse_obj({
            "deleted_orders": [DeletedOrderInfo.from_dict(_item) for _item in obj.get("deletedOrders")] if obj.get("deletedOrders") is not None else None,
            "errors": [OrderErrorInfo.from_dict(_item) for _item in obj.get("errors")] if obj.get("errors") is not None else None
        })
        return _obj


