# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt

class DimensionsRequest(BaseModel):
    """
    It is not mandatory to include the dimensions field. If the dimensions field is included then the inner fields heightInMms, widthInMms and depthInMms must be specified with non-zero values.  # noqa: E501
    """
    height_in_mms: StrictInt = Field(default=..., alias="heightInMms")
    width_in_mms: StrictInt = Field(default=..., alias="widthInMms")
    depth_in_mms: StrictInt = Field(default=..., alias="depthInMms")
    __properties = ["heightInMms", "widthInMms", "depthInMms"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DimensionsRequest:
        """Create an instance of DimensionsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DimensionsRequest:
        """Create an instance of DimensionsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DimensionsRequest.parse_obj(obj)

        _obj = DimensionsRequest.parse_obj({
            "height_in_mms": obj.get("heightInMms"),
            "width_in_mms": obj.get("widthInMms"),
            "depth_in_mms": obj.get("depthInMms")
        })
        return _obj


