# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from click_and_drop_api.models.create_packages_response import CreatePackagesResponse

class GetOrderInfoResource(BaseModel):
    """
    GetOrderInfoResource
    """
    order_identifier: StrictInt = Field(default=..., alias="orderIdentifier")
    order_reference: Optional[StrictStr] = Field(default=None, alias="orderReference")
    created_on: datetime = Field(default=..., alias="createdOn")
    order_date: Optional[datetime] = Field(default=None, alias="orderDate")
    printed_on: Optional[datetime] = Field(default=None, alias="printedOn")
    manifested_on: Optional[datetime] = Field(default=None, alias="manifestedOn")
    shipped_on: Optional[datetime] = Field(default=None, alias="shippedOn")
    tracking_number: Optional[StrictStr] = Field(default=None, alias="trackingNumber")
    packages: Optional[conlist(CreatePackagesResponse)] = None
    __properties = ["orderIdentifier", "orderReference", "createdOn", "orderDate", "printedOn", "manifestedOn", "shippedOn", "trackingNumber", "packages"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetOrderInfoResource:
        """Create an instance of GetOrderInfoResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in packages (list)
        _items = []
        if self.packages:
            for _item in self.packages:
                if _item:
                    _items.append(_item.to_dict())
            _dict['packages'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetOrderInfoResource:
        """Create an instance of GetOrderInfoResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetOrderInfoResource.parse_obj(obj)

        _obj = GetOrderInfoResource.parse_obj({
            "order_identifier": obj.get("orderIdentifier"),
            "order_reference": obj.get("orderReference"),
            "created_on": obj.get("createdOn"),
            "order_date": obj.get("orderDate"),
            "printed_on": obj.get("printedOn"),
            "manifested_on": obj.get("manifestedOn"),
            "shipped_on": obj.get("shippedOn"),
            "tracking_number": obj.get("trackingNumber"),
            "packages": [CreatePackagesResponse.from_dict(_item) for _item in obj.get("packages")] if obj.get("packages") is not None else None
        })
        return _obj


