# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, validator

class ManifestDetailsResponse(BaseModel):
    """
    ManifestDetailsResponse
    """
    manifest_number: Union[StrictFloat, StrictInt] = Field(default=..., alias="manifestNumber")
    status: Optional[StrictStr] = None
    document_pdf: Optional[StrictStr] = Field(default=None, alias="documentPdf", description="manifest in format base64 string")
    __properties = ["manifestNumber", "status", "documentPdf"]

    @validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('In Progress', 'Completed', 'Failed',):
            raise ValueError("must be one of enum values ('In Progress', 'Completed', 'Failed')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ManifestDetailsResponse:
        """Create an instance of ManifestDetailsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ManifestDetailsResponse:
        """Create an instance of ManifestDetailsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ManifestDetailsResponse.parse_obj(obj)

        _obj = ManifestDetailsResponse.parse_obj({
            "manifest_number": obj.get("manifestNumber"),
            "status": obj.get("status"),
            "document_pdf": obj.get("documentPdf")
        })
        return _obj


