# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class ManifestEligibleOrdersRequest(BaseModel):
    """
    ManifestEligibleOrdersRequest
    """
    carrier_name: Optional[StrictStr] = Field(default=None, alias="carrierName", description="The name of the carrier you would like to manifest orders for. This is required if the account has multiple carriers or multiple postage location numbers, and must match the name configured in the carrier settings within the main website. ")
    __properties = ["carrierName"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ManifestEligibleOrdersRequest:
        """Create an instance of ManifestEligibleOrdersRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ManifestEligibleOrdersRequest:
        """Create an instance of ManifestEligibleOrdersRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ManifestEligibleOrdersRequest.parse_obj(obj)

        _obj = ManifestEligibleOrdersRequest.parse_obj({
            "carrier_name": obj.get("carrierName")
        })
        return _obj


