# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class OrderFieldResponse(BaseModel):
    """
    OrderFieldResponse
    """
    field_name: Optional[StrictStr] = Field(default=None, alias="fieldName")
    value: Optional[StrictStr] = None
    __properties = ["fieldName", "value"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OrderFieldResponse:
        """Create an instance of OrderFieldResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OrderFieldResponse:
        """Create an instance of OrderFieldResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OrderFieldResponse.parse_obj(obj)

        _obj = OrderFieldResponse.parse_obj({
            "field_name": obj.get("fieldName"),
            "value": obj.get("value")
        })
        return _obj


