# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conint, constr, validator

class PostageDetailsRequest(BaseModel):
    """
    PostageDetailsRequest
    """
    send_notifications_to: Optional[StrictStr] = Field(default=None, alias="sendNotificationsTo")
    service_code: Optional[constr(strict=True, max_length=10)] = Field(default=None, alias="serviceCode")
    carrier_name: Optional[constr(strict=True, max_length=50)] = Field(default=None, alias="carrierName")
    service_register_code: Optional[constr(strict=True, max_length=2)] = Field(default=None, alias="serviceRegisterCode")
    consequential_loss: Optional[conint(strict=True, le=10000, ge=0)] = Field(default=None, alias="consequentialLoss")
    receive_email_notification: Optional[StrictBool] = Field(default=None, alias="receiveEmailNotification")
    receive_sms_notification: Optional[StrictBool] = Field(default=None, alias="receiveSmsNotification")
    guaranteed_saturday_delivery: Optional[StrictBool] = Field(default=None, alias="guaranteedSaturdayDelivery", description="This field has been deprecated")
    request_signature_upon_delivery: Optional[StrictBool] = Field(default=None, alias="requestSignatureUponDelivery")
    is_local_collect: Optional[StrictBool] = Field(default=None, alias="isLocalCollect")
    safe_place: Optional[constr(strict=True, max_length=90)] = Field(default=None, alias="safePlace")
    department: Optional[constr(strict=True, max_length=150)] = None
    air_number: Optional[constr(strict=True, max_length=50)] = Field(default=None, alias="AIRNumber", description="For B2B orders shipping from Great Britain to Northern Ireland, this field can be used to provide the Recipient UKIMs number.")
    ioss_number: Optional[constr(strict=True, max_length=50)] = Field(default=None, alias="IOSSNumber")
    requires_export_license: Optional[StrictBool] = Field(default=None, alias="requiresExportLicense")
    commercial_invoice_number: Optional[constr(strict=True, max_length=35)] = Field(default=None, alias="commercialInvoiceNumber")
    commercial_invoice_date: Optional[datetime] = Field(default=None, alias="commercialInvoiceDate")
    recipient_eori_number: Optional[StrictStr] = Field(default=None, alias="recipientEoriNumber")
    __properties = ["sendNotificationsTo", "serviceCode", "carrierName", "serviceRegisterCode", "consequentialLoss", "receiveEmailNotification", "receiveSmsNotification", "guaranteedSaturdayDelivery", "requestSignatureUponDelivery", "isLocalCollect", "safePlace", "department", "AIRNumber", "IOSSNumber", "requiresExportLicense", "commercialInvoiceNumber", "commercialInvoiceDate", "recipientEoriNumber"]

    @validator('send_notifications_to')
    def send_notifications_to_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('sender', 'recipient', 'billing',):
            raise ValueError("must be one of enum values ('sender', 'recipient', 'billing')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PostageDetailsRequest:
        """Create an instance of PostageDetailsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PostageDetailsRequest:
        """Create an instance of PostageDetailsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PostageDetailsRequest.parse_obj(obj)

        _obj = PostageDetailsRequest.parse_obj({
            "send_notifications_to": obj.get("sendNotificationsTo"),
            "service_code": obj.get("serviceCode"),
            "carrier_name": obj.get("carrierName"),
            "service_register_code": obj.get("serviceRegisterCode"),
            "consequential_loss": obj.get("consequentialLoss"),
            "receive_email_notification": obj.get("receiveEmailNotification"),
            "receive_sms_notification": obj.get("receiveSmsNotification"),
            "guaranteed_saturday_delivery": obj.get("guaranteedSaturdayDelivery"),
            "request_signature_upon_delivery": obj.get("requestSignatureUponDelivery"),
            "is_local_collect": obj.get("isLocalCollect"),
            "safe_place": obj.get("safePlace"),
            "department": obj.get("department"),
            "air_number": obj.get("AIRNumber"),
            "ioss_number": obj.get("IOSSNumber"),
            "requires_export_license": obj.get("requiresExportLicense"),
            "commercial_invoice_number": obj.get("commercialInvoiceNumber"),
            "commercial_invoice_date": obj.get("commercialInvoiceDate"),
            "recipient_eori_number": obj.get("recipientEoriNumber")
        })
        return _obj


