# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, constr
from click_and_drop_api.models.address_request import AddressRequest

class RecipientDetailsRequest(BaseModel):
    """
    RecipientDetailsRequest
    """
    address: Optional[AddressRequest] = None
    phone_number: Optional[constr(strict=True, max_length=25)] = Field(default=None, alias="phoneNumber")
    email_address: Optional[constr(strict=True, max_length=254)] = Field(default=None, alias="emailAddress")
    address_book_reference: Optional[constr(strict=True, max_length=100)] = Field(default=None, alias="addressBookReference", description="The presence or not of <b>addressBookReference</b> and a valid <b>recipient address object</b> in the request body will determine which of the following behaviours occur:-</br></br>1) addressBookReference <b>provided</b> and a valid recipient address object <b>provided</b> - In addition to the provided recipient address fields being used for the order creation, an existing account Address Book Reference with matching addressBookReference will be overwritten with all provided recipient address fields, including phone and email. If no existing account Address Book Reference with matching addressBookReference can be found then a new one will be created with the provided addressBookReference and address fields, including phone and email.</br>2) addressBookReference <b>provided</b> and a valid recipient address object <b>not provided</b> - An account Address Book Reference with the provided addressBookReference will be used for the order if it exists.</br>3) addressBookReference <b>not provided</b> and a valid recipient address object <b>provided</b> - All provided recipient address fields, including phone and email, will be used for the order creation.</br>4) All other scenarios will result in a validation error.")
    __properties = ["address", "phoneNumber", "emailAddress", "addressBookReference"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RecipientDetailsRequest:
        """Create an instance of RecipientDetailsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RecipientDetailsRequest:
        """Create an instance of RecipientDetailsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RecipientDetailsRequest.parse_obj(obj)

        _obj = RecipientDetailsRequest.parse_obj({
            "address": AddressRequest.from_dict(obj.get("address")) if obj.get("address") is not None else None,
            "phone_number": obj.get("phoneNumber"),
            "email_address": obj.get("emailAddress"),
            "address_book_reference": obj.get("addressBookReference")
        })
        return _obj


