# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ServiceItem(BaseModel):
    """
    ServiceItem
    """ # noqa: E501
    carrier_guid: Optional[UUID] = Field(default=None, alias="carrierGuid", json_schema_extra={"examples": ["e90e87c8-4ea6-49ec-a387-64ba37f66d84"]})
    carrier_service_guid: Optional[UUID] = Field(default=None, alias="carrierServiceGuid", json_schema_extra={"examples": ["3824a10c-1a2b-4e66-b82f-efa236a86cd9"]})
    service_name: Optional[StrictStr] = Field(default=None, alias="serviceName", json_schema_extra={"examples": ["Tracked Returns 24"]})
    service_code: Optional[StrictStr] = Field(default=None, alias="serviceCode", json_schema_extra={"examples": ["TSN"]})
    __properties: ClassVar[List[str]] = ["carrierGuid", "carrierServiceGuid", "serviceName", "serviceCode"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "carrierGuid": obj.get("carrierGuid"),
            "carrierServiceGuid": obj.get("carrierServiceGuid"),
            "serviceName": obj.get("serviceName"),
            "serviceCode": obj.get("serviceCode")
        })
        return _obj


