# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conint, conlist
from click_and_drop_api.models.dimensions_request import DimensionsRequest
from click_and_drop_api.models.product_item_request import ProductItemRequest

class ShipmentPackageRequest(BaseModel):
    """
    ShipmentPackageRequest
    """
    weight_in_grams: conint(strict=True, le=30000, ge=1) = Field(default=..., alias="weightInGrams")
    package_format_identifier: StrictStr = Field(default=..., alias="packageFormatIdentifier", description="<b>If you have a ChannelShipper account, you can also pass the name of any of your custom package formats instead of the values below.</b><br> Enum: 'undefined', 'letter', 'largeLetter', 'smallParcel', 'mediumParcel', 'largeParcel', 'parcel', 'documents'")
    custom_package_format_identifier: Optional[StrictStr] = Field(default=None, alias="customPackageFormatIdentifier", description="This field will be deprecated in the future. Please use 'packageFormatIdentifier' for custom package formats from ChannelShipper.")
    dimensions: Optional[DimensionsRequest] = None
    contents: Optional[conlist(ProductItemRequest)] = None
    __properties = ["weightInGrams", "packageFormatIdentifier", "customPackageFormatIdentifier", "dimensions", "contents"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ShipmentPackageRequest:
        """Create an instance of ShipmentPackageRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of dimensions
        if self.dimensions:
            _dict['dimensions'] = self.dimensions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in contents (list)
        _items = []
        if self.contents:
            for _item in self.contents:
                if _item:
                    _items.append(_item.to_dict())
            _dict['contents'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ShipmentPackageRequest:
        """Create an instance of ShipmentPackageRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ShipmentPackageRequest.parse_obj(obj)

        _obj = ShipmentPackageRequest.parse_obj({
            "weight_in_grams": obj.get("weightInGrams"),
            "package_format_identifier": obj.get("packageFormatIdentifier"),
            "custom_package_format_identifier": obj.get("customPackageFormatIdentifier"),
            "dimensions": DimensionsRequest.from_dict(obj.get("dimensions")) if obj.get("dimensions") is not None else None,
            "contents": [ProductItemRequest.from_dict(_item) for _item in obj.get("contents")] if obj.get("contents") is not None else None
        })
        return _obj


