# coding: utf-8

# flake8: noqa

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "LabelsApi",
    "ManifestsApi",
    "OrdersApi",
    "VersionApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddressRequest",
    "BillingDetailsRequest",
    "CreateOrderErrorResponse",
    "CreateOrderLabelErrorResponse",
    "CreateOrderRequest",
    "CreateOrderResponse",
    "CreateOrdersRequest",
    "CreateOrdersResponse",
    "CreatePackagesResponse",
    "DeleteOrdersResource",
    "DeletedOrderInfo",
    "DimensionsRequest",
    "ErrorResponse",
    "FailedOrderResponse",
    "GetOrderDetailsResource",
    "GetOrderInfoResource",
    "GetOrderLineResult",
    "GetOrdersDetailsResponse",
    "GetOrdersResponse",
    "GetPostalDetailsResult",
    "GetShippingDetailsResult",
    "GetTagDetailsResult",
    "GetVersionResource",
    "Importer",
    "LabelGenerationRequest",
    "ManifestDetailsResponse",
    "ManifestEligibleOrdersRequest",
    "ManifestErrorsErrorDetailsResponse",
    "ManifestErrorsResponse",
    "ManifestOrdersResponse",
    "OrderErrorInfo",
    "OrderErrorResponse",
    "OrderFieldResponse",
    "OrderUpdateError",
    "PostageDetailsRequest",
    "ProductItemRequest",
    "RecipientDetailsRequest",
    "SenderDetailsRequest",
    "ShipmentPackageRequest",
    "TagRequest",
    "UpdateOrderStatusRequest",
    "UpdateOrderStatusResponse",
    "UpdateOrdersStatusRequest",
    "UpdatedOrderInfo",
]

# import apis into sdk package
from click_and_drop_api.api.labels_api import LabelsApi as LabelsApi
from click_and_drop_api.api.manifests_api import ManifestsApi as ManifestsApi
from click_and_drop_api.api.orders_api import OrdersApi as OrdersApi
from click_and_drop_api.api.version_api import VersionApi as VersionApi

# import ApiClient
from click_and_drop_api.api_response import ApiResponse as ApiResponse
from click_and_drop_api.api_client import ApiClient as ApiClient
from click_and_drop_api.configuration import Configuration as Configuration
from click_and_drop_api.exceptions import OpenApiException as OpenApiException
from click_and_drop_api.exceptions import ApiTypeError as ApiTypeError
from click_and_drop_api.exceptions import ApiValueError as ApiValueError
from click_and_drop_api.exceptions import ApiKeyError as ApiKeyError
from click_and_drop_api.exceptions import ApiAttributeError as ApiAttributeError
from click_and_drop_api.exceptions import ApiException as ApiException

# import models into sdk package
from click_and_drop_api.models.address_request import AddressRequest as AddressRequest
from click_and_drop_api.models.billing_details_request import BillingDetailsRequest as BillingDetailsRequest
from click_and_drop_api.models.create_order_error_response import CreateOrderErrorResponse as CreateOrderErrorResponse
from click_and_drop_api.models.create_order_label_error_response import CreateOrderLabelErrorResponse as CreateOrderLabelErrorResponse
from click_and_drop_api.models.create_order_request import CreateOrderRequest as CreateOrderRequest
from click_and_drop_api.models.create_order_response import CreateOrderResponse as CreateOrderResponse
from click_and_drop_api.models.create_orders_request import CreateOrdersRequest as CreateOrdersRequest
from click_and_drop_api.models.create_orders_response import CreateOrdersResponse as CreateOrdersResponse
from click_and_drop_api.models.create_packages_response import CreatePackagesResponse as CreatePackagesResponse
from click_and_drop_api.models.delete_orders_resource import DeleteOrdersResource as DeleteOrdersResource
from click_and_drop_api.models.deleted_order_info import DeletedOrderInfo as DeletedOrderInfo
from click_and_drop_api.models.dimensions_request import DimensionsRequest as DimensionsRequest
from click_and_drop_api.models.error_response import ErrorResponse as ErrorResponse
from click_and_drop_api.models.failed_order_response import FailedOrderResponse as FailedOrderResponse
from click_and_drop_api.models.get_order_details_resource import GetOrderDetailsResource as GetOrderDetailsResource
from click_and_drop_api.models.get_order_info_resource import GetOrderInfoResource as GetOrderInfoResource
from click_and_drop_api.models.get_order_line_result import GetOrderLineResult as GetOrderLineResult
from click_and_drop_api.models.get_orders_details_response import GetOrdersDetailsResponse as GetOrdersDetailsResponse
from click_and_drop_api.models.get_orders_response import GetOrdersResponse as GetOrdersResponse
from click_and_drop_api.models.get_postal_details_result import GetPostalDetailsResult as GetPostalDetailsResult
from click_and_drop_api.models.get_shipping_details_result import GetShippingDetailsResult as GetShippingDetailsResult
from click_and_drop_api.models.get_tag_details_result import GetTagDetailsResult as GetTagDetailsResult
from click_and_drop_api.models.get_version_resource import GetVersionResource as GetVersionResource
from click_and_drop_api.models.importer import Importer as Importer
from click_and_drop_api.models.label_generation_request import LabelGenerationRequest as LabelGenerationRequest
from click_and_drop_api.models.manifest_details_response import ManifestDetailsResponse as ManifestDetailsResponse
from click_and_drop_api.models.manifest_eligible_orders_request import ManifestEligibleOrdersRequest as ManifestEligibleOrdersRequest
from click_and_drop_api.models.manifest_errors_error_details_response import ManifestErrorsErrorDetailsResponse as ManifestErrorsErrorDetailsResponse
from click_and_drop_api.models.manifest_errors_response import ManifestErrorsResponse as ManifestErrorsResponse
from click_and_drop_api.models.manifest_orders_response import ManifestOrdersResponse as ManifestOrdersResponse
from click_and_drop_api.models.order_error_info import OrderErrorInfo as OrderErrorInfo
from click_and_drop_api.models.order_error_response import OrderErrorResponse as OrderErrorResponse
from click_and_drop_api.models.order_field_response import OrderFieldResponse as OrderFieldResponse
from click_and_drop_api.models.order_update_error import OrderUpdateError as OrderUpdateError
from click_and_drop_api.models.postage_details_request import PostageDetailsRequest as PostageDetailsRequest
from click_and_drop_api.models.product_item_request import ProductItemRequest as ProductItemRequest
from click_and_drop_api.models.recipient_details_request import RecipientDetailsRequest as RecipientDetailsRequest
from click_and_drop_api.models.sender_details_request import SenderDetailsRequest as SenderDetailsRequest
from click_and_drop_api.models.shipment_package_request import ShipmentPackageRequest as ShipmentPackageRequest
from click_and_drop_api.models.tag_request import TagRequest as TagRequest
from click_and_drop_api.models.update_order_status_request import UpdateOrderStatusRequest as UpdateOrderStatusRequest
from click_and_drop_api.models.update_order_status_response import UpdateOrderStatusResponse as UpdateOrderStatusResponse
from click_and_drop_api.models.update_orders_status_request import UpdateOrdersStatusRequest as UpdateOrdersStatusRequest
from click_and_drop_api.models.updated_order_info import UpdatedOrderInfo as UpdatedOrderInfo

